.test_front_template: &test_front_definition
  stage: test
  before_script:
    - node --version
    - yarn --version
  script:
    - cd jscraper-ui && yarn install && yarn lint
  only:
    - master

stages:
  - test
  - deploy-back
  - deploy-front

#tests:node-6:
#  <<: *test_front_definition
#  image: node:6-alpine
#
#tests:node-7:
#  <<: *test_front_definition
#  image: node:7-alpine

tests:node-8:
  <<: *test_front_definition
  image: node:8-alpine

deploy:back:
  stage: deploy-back
  image: ubikz/docker-ssh-remote-exec:alpine
  script:
    - ssh root@ubikz.com "cd dockers/jscraper && git pull origin master && make prod"
  only:
    - master

deploy:front-latest:
  stage: deploy-front
  image: ubikz/docker-aws-static-deploy:2.7.8
  before_script:
    - cd jscraper-ui
    - node --version
    - yarn --version
    - yarn install
    - export API_HOST=$API_HOST && yarn prod
  script:
    - bash ./scripts/aws-ci.sh
  only:
    - master