jscraper:
  build: .
  container_name: jscraper-api
  links:
    - pgsql
  ports:
      - "3000:3000"
      - "5005:5005"
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/.m2:/root/.m2
  environment:
    - VIRTUAL_HOST=jscraper.localhost
  env_file: .env
pgsql:
  image: postgres:9-alpine
  container_name: jscraper-pgsql
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
    - ./pgsql/initdb.d:/docker-entrypoint-initdb.d:ro
  env_file: .env
