nginx:
  build: nginx
  ports:
    - "80:80"
  links:
    - jscraper
  volumes_from:
      - jscraper-ui
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/nginx:/var/log/nginx
  env_file: .env
jscraper:
  build: jscraper
  links:
    - pgsql
  ports:
      - "3000:3000"
      - "5005:5005"
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/gradle:/jscraper/cache
  env_file: .env
pgsql:
  image: postgres:9.6.2-alpine
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
    - ./pgsql/initdb.d:/docker-entrypoint-initdb.d:ro
  env_file: .env
jscraper-ui:
  build: jscraper-ui
  volumes:
    - ./docker/scraper-ui:/var/www/jscraper
  env_file: .env
