jscraper:
  build: jscraper
  links:
    - pgsql
  ports:
      - "3000:3000"
      - "5005:5005"
  volumes_from:
      - jscraper-ui
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/gradle:/jscraper/cache
      - ./docker/scraper/nginx:/nginx
  env_file: .env
pgsql:
  image: postgres:9.6.2-alpine
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
    - ./pgsql/initdb.d:/docker-entrypoint-initdb.d:ro
  env_file: .env
jscraper-ui:
  build: jscraper-ui
  volumes:
    - ./docker/scraper-ui:/jscraper/scraper/src/main/resources/static
