jscraper:
  build: jscraper
  links:
    - pgsql
  ports:
      - "3000:3000"
      - "5005:5005"
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/gradle:/jscraper/cache
      - ./docker/scraper/nginx:/nginx
  env_file: .env
pgsql:
  image: postgres:9.6.1-alpine
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
  env_file: .env