jscraper:
  image: ubikz/jscraper
  links:
    - pgsql
  ports:
      - "3000:3000"
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/gradle:/jscraper/cache
      - ./docker/scraper/nginx:/nginx
  env_file: .env
  log_opt:
    max-size: "100k"
pgsql:
  image: postgres:9.6.2-alpine
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
    - ./pgsql/initdb.d:/docker-entrypoint-initdb.d:ro
  env_file: .env
  log_opt:
    max-size: "100k"
jscraper-ui:
  image: ubikz/jscraper-ui
  volumes:
    - /jscraper/scraper/src/main/resources/static