nginx:
  image: ubikz/jscraper-nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - jscraper
  volumes_from:
    - jscraper-ui
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/nginx:/var/log/nginx
  env_file: .env
jscraper:
  image: ubikz/jscraper
  links:
    - pgsql
  ports:
      - "3000:3000"
  volumes:
      - ./docker/scraper/log:/var/log
      - ./docker/scraper/gradle:/jscraper/cache
  env_file: .env
  log_opt:
    max-size: "100k"
pgsql:
  image: postgres:9.6.2-alpine
  ports:
    - "5432:5432"
  volumes:
    - ./docker/pgsql/data:/var/lib/postgresql/data
    - ./pgsql/initdb.d:/docker-entrypoint-initdb.d:ro
  env_file: .env
  log_opt:
    max-size: "100k"
jscraper-ui:
  image: ubikz/jscraper-ui
  volumes:
    - /jscraper/scraper/src/main/resources/static